import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>TikTik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-3xl font-bold'>
        hello
      </h1>

      
    </div>
  )
}
